[package]
name = "tomcatctl"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
color-eyre = "0.6.3"
ctrlc = "3.4.5"
glob = "0.3.1"
serde = { version = "1.0.215", features = ["derive"] }
tabled = "0.17.0"
toml = "0.8.19"
xml-rs = "0.8.23"
